[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
"@openzeppelin-contracts" = "5.2.0-rc.1"

[soldeer]
# whether soldeer manages remappings
remappings_generate = true

# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false

# whether to suffix the remapping with the version: `name-a.b.c`
remappings_version = false

# where to store the remappings ("txt" for `remappings.txt` or "config" for `foundry.toml`)
# ignored when `soldeer.toml` is used as config (uses `remappings.txt`)
remappings_location = "txt"

# Install all subdependencies
recursive_deps = true
